# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Question.create(content:"Collect Every Letter In The Alphabet" , points: 300, answer:"ABCDEFGHIJKLMNOPQRSTUVWXYZ")
Question.create(content: "Are bananas fruits or vegetables?", points: 5, answer: "FRUIT")
Question.create(content: "Babe Ruth is associated with which sport?", points: 10, answer:"BASEBALL")
Question.create(content: "In 2019, which middle eastern country launched a spacecraft going to the moon?", points: 8, answer:"ISRAEL")
Question.create(content: "Which animal is known to kill more people than plane crashes?", points: 15, answer:"DONKEY")
Question.create(content: "Babe Ruth is associated with which sport?", points: 10, answer:"BASEBALL")
Question.create(content: "Traditionally, how many Wonders of the World are there?", points: 8, answer:"SEVEN")
Question.create(content: "What is the name of the fairy in Peter Pan?", points: 35 , answer:"TINKERBELL")
Question.create(content: "Who is the founder of Facebook?", points: 50 , answer:"MARKZUCKERBERG")
Question.create(content: "In which state is the Grand Canyon?", points: 15 , answer:"ARIZONA")
Question.create(content: "Which 1997 science fiction movie starring Will Smith and Tommy Lee Jones tells the story of a secret agency that polices alien refugees who are living on earth disguised as humans?", points: 3 , answer:"MIB")
Question.create(content: "What's the antonym of 'synonym'?", points: 20 , answer:"ANTONYM")
Question.create(content: "Who was the drummer in the Beatles?", points: 5 , answer:"RINGO")
Question.create(content: "How is Robert Zimmerman better known?", points: 10 , answer:"BOBDYLAN")
Question.create(content: "What is the name of this game?", points: 50 , answer:"QUIZALCOATL")
Question.create(content: "Who is the Meso-American God of Wind and Wisdom?", points: 50 , answer:"QUETZALCOATL")
Question.create(content: "Which famous music group were formerly known as the New Yardbirds?", points: 25 , answer:"LEDZEPPELIN")
Question.create(content: "Dwayne the .... Johnson", points: 10 , answer:"ROCK")
Question.create(content: "In the show How I Met Your Mother, where is Robin Scherbatsky from?", points: 24 , answer:"CANADA")
Question.create(content: "In the movie Home Alone, what is the young boys first name?", points: 15 , answer:"KEVIN")
User.create(username: "snakeboi")
Score.create(scoreValue: 0, user_id: 1)
Score.create(scoreValue: 0, user_id: 1)
Score.create(scoreValue: 0, user_id: 1)
Score.create(scoreValue: 0, user_id: 1)
Score.create(scoreValue: 0, user_id: 1)
Score.create(scoreValue: 0, user_id: 1)
Score.create(scoreValue: 0, user_id: 1)
Score.create(scoreValue: 0, user_id: 1)
Score.create(scoreValue: 0, user_id: 1)
Score.create(scoreValue: 0, user_id: 1)
Score.create(scoreValue: 0, user_id: 1)
